- name: ping servers
  hosts: all
  become: false
  tasks:
    - name: ping all servers
      ping:

- name: install app
  hosts: first_server
  become: true
  gather_facts: false
  tasks:
    - name: dependecies
      raw: apt-get update && apt install -y python3 python3-pip openssh-server sshpass openssh-client
    - name: clone repo
      raw: git clone https://github.com/MichaelGon/OS_HW_2.git && cd OS_HW_2 && git checkout dev
    - name: install app
      raw: mkdir -p /app && cp -r /OS_HW_2/app/* /app

- name: first_server running
  hosts: first_server
  become: true
  gather_facts: false
  tasks:
    - server_1
